### ISSUE TITLE
Java Platform SE Binary stopped working

### ISSUE THREAD

**Issue by PhilDa** [Audiveris/audiveris#18]
Hi,
I went through a relatively long process to setup Audiveris, and succeeded to get it run. But there is no way to use it; Java crashes directly when trying to open a menu item (just hovering on the menu, not even clicking on it) "Java(TM) Platform SE Binary a cessé de fonctionner".
Steps followed:
- installation of Java 8.131 and Java SDK 8.131 (64 bits) on Windows 10 64 bits (removing previous versions and re-installing)
- installation of Git 2.13.0
- installation of Gradle
- Initial "gradle build" failed due to same issue as #15 Can't run Audiveris
- "git clone https://github.com/Audiveris/audiveris.git" ok
- "grade build" failed during test with Ghostscript
- installation Ghostscript 9.1
- "Gradle build" ok
- "gradle run": ok but "Java Platform SE Binary stopped working while hovering on the menu
- several trials to rebuild ("gradle :clean" and then "gradle build"): no change.
- delete audiveris folder, new Git clone, gradle build and gradle run: no change

I attach the "gradle build" trace and the "gradle run -stacktrace".
[build_23052017.txt](https://github.com/Audiveris/audiveris/files/1023806/build_23052017.txt)
[run_stacktrace_23052017.txt](https://github.com/Audiveris/audiveris/files/1023807/run_stacktrace_23052017.txt)

**Comment by Foolius** [comment]
Did you install tesseract as stated in the readme?

**Comment by PhilDa** [comment]
I forgot to mention! Tesseract-OCR 3.05.01 installed, before the build(s) mentioned above.

**Comment by maximumspatium** [comment]
1. Clear Gradle and Maven caches (locations are system dependent).
2. switch to the development branch (`git checkout development`)
3. rebuild Audiveris (`gradle clean run`)

If the above mentioned steps don't help post the JVM stack trace after the crash here...

**Comment by PhilDa** [comment]
No clue how to clean caches (I checked on Internet and on Gradle help), so I deleted the whole Audiveris folder (may be the cache files are located elsewhere?)
- Gradle clone (it created again the Audiveris directory)
- cd Audiveris
- git checkout development
- gradle clean run (everything seems ok) -> crash
- Outcome of gradle run -stacktrace posted:
[run_stacktrace_24052017.txt](https://github.com/Audiveris/audiveris/files/1025531/run_stacktrace_24052017.txt)

**Comment by PhilDa** [comment]
- Found gradle cache on c:\users\username\.gradle\caches (maven cache still not found)
- Deleted the "caches" directory (need to stop the running Java instance)
- gradle clean run -> crash
- gradle run -stacktrace:
[run_stacktrace_24052017_2.txt](https://github.com/Audiveris/audiveris/files/1025661/run_stacktrace_24052017_2.txt)

**Comment by maximumspatium** [comment]
What does `gradle -v` say?

**Comment by PhilDa** [comment]
gradle -v
[gradle_v.txt](https://github.com/Audiveris/audiveris/files/1027210/gradle_v.txt)

**Comment by maximumspatium** [comment]
You can also try to downgrade the Java SDK to said build 121. If it doesn't help, try to downgrade Gradle to v3.3. I hope you'll succeed. I'll try to reproduce your build environment in my Windows 7...

**Comment by PhilDa** [comment]
Regarding GhostScript, I do not remember all the details, but  it might be that I got the problem in a previous trial, getting issue #16, solved by "git checkout development". No more the case now (but I have Ghostscript installed...).
Actions taken:
- Uninstall Java 8 update 1.3.1 (64-bit)
- Uninstall Java SE Development Kit 8 Update 1.3.1 (64-bit)
- Install Java 8 Update 1.2.1 (looks like it installs both 32 and 64 bits)
- Install Java SE Development Kit 8 Update 1.2.1 (64-bit)
- "Gradle build" fails on ":processResources" (Could not copy file ...\Thumbs.db" to "...")
- "Gradle clean build" ok
- "Gradle run" crashes.

- Install Gradle 3.3, clean build, run -> crash

- Move again to Java and JDK 1.3.1, gradle clean build (problem with "MouseWheelTest"? Second trial with Gradle Build is ok...), but still same crash.

Looking forward to your feed-back on Windows 7.
In any case, thank you for your support.

**Comment by maximumspatium** [comment]
Try the following:

```
gradle clean build
cd build/distributions
unzip Audiveris.zip
./Audiveris.bat
```
Does Audiveris still crash? If yes, please post the stack trace once again...

**Comment by PhilDa** [comment]
- gradle clean build
- cd build\distributions
- unzipped Audiveris.zip from there, which means that Audiveris.bat was located on ...\Audiveris\build\distribution\Audiveris\Audiveris\bin\
- did ".\Audiveris.bat". Got "La ligne d'entrée est trop longue. La syntaxe de la commande n'est pas correcte" (Entry ligne is too long. Command syntax in not correct)
- setup environment variable DEBUG to get trace:
[Audiveris.txt](https://github.com/Audiveris/audiveris/files/1036673/Audiveris.txt)
(I also tried by moving Audiveris.bat to first Audiveris directory, but same error

**Comment by garu57** [comment]
@PhilDa 
The `Audiveris.bat ` cannot be run the way it is. The CLASSPATH line is way too longer than Windows allowed maximum.
Locate the line that starts with `set CLASSPATH=` remove it and substitute it with 
`set CLASSPATH=%APP_HOME%\lib\*
`
Then you can launch Audiveris with the bat.

But i don't think you will get too far. I think that both the master and development branches still have some problems. 
May be it's me that i'm doing something wrong, but i tried to follow exactly the instructions in the provided handbook and selected glyphs and sections gets unselected as soon as i right click on them to get the context menu and any action from the boards ends in a stack trace or a "Not Implemented" message, so i couldn't correct any error in the parsed scores (i tried only some of the provided examples).

Regards,
Gabriele

**Comment by maximumspatium** [comment]
> Then you can launch Audiveris with the bat.

Thank you for your help. I suggested to launch Audiveris using the .bat in order to sort out installation issues with Java/Gradle PhilDa definitely experiencing.

> But i don't think you will get too far. I think that both the master and development branches still have some problems.

Please be more specific and don't pollute issue tickets with unrelated comments. If you feel Audiveris doesn't work for you as expected, please open a new issue (or several issues for each specific problem) so we can solve them step by step. Thanks.

**Comment by garu57** [comment]
@maximumspatium 
I'm sorry, you are rigth.
I'll shut up. I promise.
Gabriele

**Comment by PhilDa** [comment]
Thank you both. Things are going better.
- change proposed to the .bat did not work (APP_HOME ends with "\.."), so I changed the line to
- `set CLASSPATH=%DIRNAME%lib\*`
-  ran`.\audiveris.bat`, or `audiveris.bat`
- Good news! The appli does not crash any more (at least trying with some menu items, such as "help/about")
- Less good news. There are error messages before application runs:
[Batch.txt](https://github.com/Audiveris/audiveris/files/1046151/Batch.txt)
as well as in the lower left pane ("_Error loading alias patterns java.io.FileNotFoundException_" on file _alias-pattern.xml_). I do not know if the application will behave as expected...


- can you tell whether these errors are critical?
- would the crashes be because the CLASSPATH was not properly defined?

**Comment by PhilDa** [comment]
- Looking at the errors, I copied the directory "audiveris\config", containing "logback.xml", to "users\philippe\AppData\roaming\AudiverisLtd\audiveris"
- script execution is better; one main error ("URI is not hierarchical"): 
[run1.txt](https://github.com/Audiveris/audiveris/files/1046189/run1.txt)
- but critical problem while trying with a sample file ("example\allegretto.png") "cannot unmarchal script": [run1.txt](https://github.com/Audiveris/audiveris/files/1046198/run1.txt)
- also, when trying to open the sample file, the file selector is starting on the "users\philippe\AppData\roaming\AudiverisLtd\audiveris\data" directory, which is not very handy, since I start the application from the "documents\Audiveris\Audiveris" directory, where my samples are supposed to be stored. Is it normal?

**Comment by hbitteur** [comment]
@PhilDa Could you try the "release-5.0" branch, where the accesses to 'res' and 'config' should now be fixed.

Also have a look at the wiki, especially https://github.com/Audiveris/audiveris/wiki/CLI-Arguments#-output, to understand how output targets are handled and how you can modify them.

**Comment by PhilDa** [comment]
Hi. Sorry for late feed-back. I made some tests.

Branch "release-5.0" did not help. 
I did not see any helpfull info in the wiki (including CLI-Arguments).

Tests done since then (July, August):

- Clean directory
- git clone https://github.com/Audiveris/audiveris.git
- gradle clean build
- gradle run -> same error

Remove previous Tesseract and Install Tesseract 4
- gradle
- run - same error

- gradle clean
- gradle build
- gradle run - same error

- Clean directory
- git clone https://github.com/Audiveris/audiveris.git
- cd audiveris
- git checkout development
- gradle clean build

- Install procedure (unzip Audiveris.zip from build/distribution to C:\audiveris)
- run Audiveris.bat from C:\bin\Audiveris\bin directory -> same problem

**Comment by hbitteur** [comment]
Anything new?
Could you tell us the current status of this issue?

**Comment by PhilDa** [comment]
Hello Hervé,

Good news!

I stopped spending time on Audiveris since I could not have it working. 

However, after your mail today, I tried again with the latest version. No error at build, nor at run. Nothing changed to my config (same Java, Tesseract, Gradle...). And now, it works! I have been able to load a score and export it to MuseScore. No clue why it was not working before.

Thank you for your work on Audiveris and support on this issue.

Philippe
