### ISSUE TITLE
staccato

### ISSUE THREAD

**Issue by CCturner** [Audiveris/audiveris#198]
Staccato notes are recognised but the staccato notation is not included in xml files.  
[Cake walk - descant.pdf](https://github.com/Audiveris/audiveris/files/2318616/Cake.walk.-.descant.pdf)

**Comment by Bacchushlg** [comment]
This error had been fixed in July this year.
Please try again with the actual version. I did so and everything worked fine.

**Comment by CCturner** [comment]
Hi Baruch,

 

Thank you for your quick reply.

 

I downloaded the latest version from the web today but staccatos are still missing in xml file. (I use MuseScore)

 

Regards

**Comment by Bacchushlg** [comment]
are you sure about your version?
Please look at "Help|About": You should see version 5.1.0:9fa751d43

**Comment by CCturner** [comment]
Hi Maxim,

 

Success.  This feature has not transferred from development to master.

 

FYI.  The plugin menu described in help documentation is not available in either master or development. Not a personal problem.

 

Regards

**Comment by maximumspatium** [comment]
> Success.

Alright. The issue can be closed.
