### ISSUE TITLE
Audiveris build from development branch doesn't work

### ISSUE THREAD

**Issue by SofNotenwart** [Audiveris/audiveris#699]
The stable version of Audiveris (5.3.1:5aa4d06dc) didn’t provide a satisfactory result, see my previous ticket https://github.com/Audiveris/audiveris/issues/697 . 

I therefore tried to build Audiveris from the development branch and followed the steps defined in the handbook, i.e.
https://audiveris.github.io/audiveris/_pages/install/sources/#building-from-sources-windows-macos-linux-archlinux 

As far as I can see, the installation and build went well without any errors, see attached log _AudiverisDevelopmentBuild.log_.  My setup is as shown below which is an excerpt from the log addressed above.  Also here, no error messages.

```
> Configure project :
targetOS=windows-x86_64

> Task :run
INFO  []                       CLI 282  | CLI args: []
INFO  []              TesseractOCR 116  | TESSDATA_PREFIX value: null
INFO  []                      Main 402  | Environment:
- Audiveris:    5.4-alpha:b08ae853b
- OS:           Windows 11 10.0
- Architecture: amd64
- Java VM:      Java HotSpot(TM) 64-Bit Server VM (build 17.0.9+11-LTS-201, mixed mode, sharing)
- OCR Engine:   Tesseract OCR, version 5.3.1
INFO  []             AliasPatterns 134  | Alias patterns: [(IMSLP[0-9]*)-.*]
INFO  []                   MainGui 564  | Audiveris version 5.4-alpha
INFO  []                   MainGui 565  |
LogUtil. Property logback.configurationFile not defined, skipped.
LogUtil. No C:\Users\tommy\AppData\Roaming\AudiverisLtd\audiveris\config\logback.xml, skipped.
LogUtil. Configuration found file:///C:/Users/tommy/audiveris/res/logback.xml
LogUtil. Logging to C:\Users\tommy\AppData\Roaming\AudiverisLtd\audiveris\log\20231114T105918.log

INFO  []           BasicClassifier 277  | Classifier loaded XML norms.
INFO  []        AbstractClassifier 396  | Classifier data loaded from default uri file:///C:/Users/tommy/audiveris/res/basic-classifier.zip
INFO  []            PluginsManager 210  | No C:\Users\tommy\AppData\Roaming\AudiverisLtd\audiveris\config\plugins.xml file found
INFO  []                  Versions 301  | Versions. Poll frequency: Weekly, next poll on: 20-Nov-2023
<==========---> 83% EXECUTING [45s]
> :run
```

I ran an OMR try of the score on a few pages of Dvorak’s symphony No. 9. The result was not good. In fact no OMR was performed at all due to, among others, an `“Error in GridBuilder:. . . . . “`, see below and for full details, the attached log.

What has gone wrong here?  I don't think it's necessary, but I attach the pdf-file as well.

[AudiverisDevelopmentBuild.log](https://github.com/Audiveris/audiveris/files/13347624/AudiverisDevelopmentBuild.log)
[OMR_FromDvorak9th_p1-5.log](https://github.com/Audiveris/audiveris/files/13347633/OMR_FromDvorak9th_p1-5.log)
[DvorakA_SinfonieNr.9_Mvnt1_p1-5.pdf](https://github.com/Audiveris/audiveris/files/13347639/DvorakA_SinfonieNr.9_Mvnt1_p1-5.pdf)

**Comment by hbitteur** [comment]
@SofNotenwart 
Sorry for this bug, I hadn't noticed a problem in cross-elaboration of Book and SheetStub classes.

Now fixed by commit 83abeee67013da9efbcba4a94c8839beb815fd3d.
Please pull from the development branch and rebuild.
And tell me if it's now OK for you too.

**Comment by SofNotenwart** [comment]
With the update performed, see above, this ticket can be closed. 

Issue https://github.com/Audiveris/audiveris/issues/697 regarding recognition quality is not resolved.

**Comment by hbitteur** [comment]
> Issue #697 regarding recognition quality is not resolved.

I know, but I'm busy on other topics.
One thing at a time! :-)

**Comment by SofNotenwart** [comment]
No problem, when I've time, I will "play" a little with the PDF inputs and Audiveris settings to see if I can get a better result. I keep you informed.
