### ISSUE TITLE
problem to detect common augmentation dots for note head common to 2 voices 

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#75]
![coharm - ein freund-stimmen-02](https://user-images.githubusercontent.com/33522630/36301824-77b48f1e-1306-11e8-9c10-54c396e191b4.jpg)

Sometimes augmentation dots are common for a note head that is identical for 2 voices.
see measure 31f.
In measure 35f there are 2 dots (very inconsistent - but it's from a "professional" score). 

In both cases, the aug. dot is only assigned to one voice - the other is exported as normal quarter note.

**Comment by hbitteur** [comment]
Fixed with issue #87 
So I close this one

**Comment by Bacchushlg** [comment]
No, this was a different task. And it is not solved, I just re-checked.

**Comment by hbitteur** [comment]
Yes you are right, this issue is a bit different from #87
It is about a dot "shared" by two mirrored heads (a single physical head, "shared" by two different chords) 
Sorry

**Comment by hbitteur** [comment]
I checked behavior of latest OMR engine (which links a dot to both mirror heads in pair).

In measure 31f, we have mirror heads with just one dot. Both heads are augmented.

In measure 35f, we have mirror heads each with its "own" dot. Both heads are augmented by the upper dot, the lower dot is simply ignored.

If so desired, it is also possible to manually assign the lower dot and link it to the "lower" head, then remove the undesired relations. In the end, we can thus have the upper dot linked to the "upper" head and the lower dot linked to the "lower" head.

I think this is OK.
